### ISSUE TITLE
Other Dataset

### ISSUE THREAD

**Issue by wjlpku** [pcy1302/DMGI#1]
Hi, I am excited to see this work which implemented Deep Graph Infomax on Multiplex Network!
And I want to test ACM, DBLP, Amazon Dataset based on your code, can you provide these data sets and code about preprocess about them? 
I will be appreciated for your reply as soon as possible, thank you very much!

**Comment by pcy1302** [comment]
Hi, thanks for you interest. I uploaded preprocessing codes. Please check them out.

**Comment by wjlpku** [comment]
Thanks for your reply, can you upload ACM and Amazon datasets?

**Comment by wjlpku** [comment]
Actually , I wonder which version of ACM you use in the URL you provide, and other details about Amazon.

**Comment by pcy1302** [comment]
1. ACM dataset is downloaded from https://github.com/Jhy1993/HAN/tree/master/data.
2. As mentioned, I used ````DBLP-Citation-network V8```` from the aminer dataset.
3. I downloaded Amazon datasets from http://jmcauley.ucsd.edu/data/amazon/links.html, and I preprocessed it similar to how I preprocessed DBLP dataset. 

Thanks

**Comment by wjlpku** [comment]
Thanks for your reply,
I also have one question(I am new to pytorch)
In models.DGI, why model.eval() not set before use model.embed()? 
Can it hurts the performance?

**Comment by pcy1302** [comment]
I don't think it will hurt the performance, because I call ````.detach()```` in ````.embed()```` function. You are welcome to try, and please let me know if it changes anything.
