### ISSUE TITLE
DBLP-V8 dataset doesn't have abstract

### ISSUE THREAD

**Issue by tonygracious** [pcy1302/DMGI#3]
I downloaded the DBLP-V8 from Aminer website. It doesn't have paper abstracts field. Can you share your raw datasets that you have used?

**Comment by pcy1302** [comment]
It seems that the link in the aminer website is broken. I uploaded the raw dataset in the following link https://drive.google.com/open?id=1ISAnMHE-qhkzvwTUl69K0os7CRbQjr3X. Feel free to download.

**Comment by chenbofeng123** [comment]
hi~ sorry to interrupt you. can you share the dataset, the link is error
