### ISSUE TITLE
Running with dataset "IMDB"

### ISSUE THREAD

**Issue by wangwenchu** [pcy1302/DMGI#5]
Dear authors :
I use the "IMDB" dataset and run the program，I didn't change the parameters, but I got the different results from your paper. So，could you help me to explain this ? The following is the result. 

DMGI:
[Classification] Macro-F1: 0.6509 (0.0101) | Micro-F1: 0.6519 (0.0076)
[Clustering] NMI: 0.2015
[Similarity] [5,10,20,50,100] : [0.6115,0.6022,0.5944,0.581,0.5674]

DMGI(attention):
[Classification] Macro-F1: 0.6163 (0.0114) | Micro-F1: 0.6184 (0.0083)
[Clustering] NMI: 0.1992
[Similarity] [5,10,20,50,100] : [0.5868,0.5754,0.5646,0.555,0.5449]

**Comment by pcy1302** [comment]
Hi, thanks for your interest in our paper.
In my opinion, the results you posted are very close to the results reported in the paper.
Your results are rather better than those reported in the paper.
Which part do you think do not match?

**Comment by wangwenchu** [comment]
Thanks , but the resuts（without attention) of dataset "ACM" are very different from the paper,I don't know why.
        [Classification] Macro-F1: 0.3385 (0.0091) | Micro-F1: 0.3402 (0.0100)
        [Clustering] NMI: 0.0010
        [Similarity] [5,10,20,50,100] : [0.3293,0.3283,0.3293,0.3317,0.3337]

**Comment by pcy1302** [comment]
I just ran the code myself on ACM dataset, and checked that the results are reproduced.

For DMGI, I got
	[Classification] Macro-F1: 0.8800 (0.0151) | Micro-F1: 0.8806 (0.0153)
	[Clustering] NMI: 0.6768
	[Similarity] [5,10,20,50,100] : [0.8951,0.8896,0.8862,0.878,0.873]

For DMGI_attn, I got
	[Classification] Macro-F1: 0.8767 (0.0128) | Micro-F1: 0.8763 (0.0128)
	[Clustering] NMI: 0.7252
	[Similarity] [5,10,20,50,100] : [0.8941,0.8917,0.8891,0.8847,0.8816]

You may want to set ````--reg_coef 0.0001````

Try this
````python main.py --embedder DMGI --dataset acm --metapaths PAP,PLP --isAttn --reg_coef 0.0001````

**Comment by wangwenchu** [comment]
Sorry,I still can't get the similar results. And I tired to change other parameters, but it did work,the results are still like before.

**Comment by pcy1302** [comment]
You could try to match the versions of Pytorch,

Python version: 3.6.8
Pytorch version: 1.2.0
networkx version: 2.3

**Comment by wenchu1995** [comment]
Sincere thanks to you, I re-downloaded  the source code and ran again, now I got the desired results. I think it has noting to do with the version of Pytorch， Maybe I accidentally modified somewhere when reading that。

**Comment by wangwenchu** [comment]
Sincere thanks to you, I re-downloaded  the source code and ran again, now I got the desired results. I think it has noting to do with the version of Pytorch,maybe I  modified somewhere by mistake when reading that。
