### ISSUE TITLE
Can you share DBLP and amazon using google drive again? 

### ISSUE THREAD

**Issue by chenbofeng123** [pcy1302/DMGI#7]
Sorry to interrupy you again, your link is error,Can you share DBLP and amazon using google drive again?

**Comment by pcy1302** [comment]
Hi, sorry for the missing link.
Please download from https://www.dropbox.com/s/48oe7shjq0ih151/data.tar.gz?dl=0

**Comment by chenbofeng123** [comment]
cool! thank you so much !
