### ISSUE TITLE
some details about dataset,

### ISSUE THREAD

**Issue by chenbofeng123** [pcy1302/DMGI#8]

**Comment by chenbofeng123** [comment]
1.in amazon dataset,i find 4 relation type named "IVI",'IBI','IOI','ITI'，what is the Also-V Also-B Bou.-T realtion type?
2.in dblp dataset,i find no PPP relation type. i want to make sure whether PPrefP  is PPP relation type?

**Comment by pcy1302** [comment]
1. IVI: Also-V, IBI: Also-B, IOI: Bou.-T. You can ignore ITI.
2. Yes

**Comment by wangqiang-codes** [comment]
In the Amazon dataset, I found that the total number of edges was 14305 (IOI). But the paper gave it as 16305. Is this data set used in the paper? Is there any difference between them? Looking forward to your reply as soon as possible. Thank you!
